### ISSUE TITLE
想咨询一下显存的消耗

### ISSUE THREAD

**Issue by liuchenxin666** [Human9000/nd-Mamba2-torch#34]
我的输入是图像（batch, channel, h, w）为（8,3,224,224）
使用模型如下：
```
from torchnssd.ex_bi_mamba2_ac import *

model = BiMamba2Ac2d(3, 128, 32)
```
我用的显卡是12G显存的4070，在forward()的这一步
```
y_h2 = self.bi_mamba_w1(x_h2).transpose(1, 2).reshape(b, w, h, -1).transpose(1, 3)
```
出现了CUDA out of memory，报错信息如下：
```
Traceback (most recent call last):
  File "D:/Programs Files/PyCharm Community Edition 2023.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Programs Files\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\Python_project\nd-Mamba2-torch-main\iqa_train.py", line 152, in <module>
    pred = model(img)
  File "D:\Programs Files\Anaconda\envs\PL-IQA\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Python_project\nd-Mamba2-torch-main\torchnssd\ex_bi_mamba2_ac.py", line 218, in forward
    y_h2 = self.bi_mamba_w1(x_h2).transpose(1, 2).reshape(b, w, h, -1).transpose(1, 3)
  File "D:\Programs Files\Anaconda\envs\PL-IQA\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Python_project\nd-Mamba2-torch-main\torchnssd\ex_bi_mamba2_ac.py", line 184, in forward
    x1 = self.mamba2_for(x)
  File "D:\Programs Files\Anaconda\envs\PL-IQA\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Python_project\nd-Mamba2-torch-main\torchnssd\ex_bi_mamba2_ac.py", line 85, in forward
    C.unsqueeze(2), )
  File "E:\Python_project\nd-Mamba2-torch-main\torchnssd\ex_bi_mamba2_ac.py", line 126, in ssd
    states = torch.einsum("bclhn, bhcl, bclhp -> bchpn", B, decay_states, x)
  File "D:\Programs Files\Anaconda\envs\PL-IQA\lib\site-packages\torch\functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB (GPU 0; 11.99 GiB total capacity; 25.08 GiB already allocated; 0 bytes free; 25.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
python-BaseException
```

**Comment by Human9000** [comment]
我的建议是，不要在刚开始就用这个mamba块，你可以先卷积，在特征下采样到64尺度一下的时候，再考虑采用mamba块



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年1月16日(周四) 晚上8:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Human9000/nd-Mamba2-torch] 想咨询一下显存的消耗 (Issue #34)




 
我的输入是图像（batch, channel, h, w）为（8,3,224,224）
 使用模型如下：
 from torchnssd.ex_bi_mamba2_ac import * model = BiMamba2Ac2d(3, 128, 32)  
我用的显卡是12G显存的4070，在forward()的这一步
 y_h2 = self.bi_mamba_w1(x_h2).transpose(1, 2).reshape(b, w, h, -1).transpose(1, 3)  
出现了CUDA out of memory，报错信息如下：
 Traceback (most recent call last):   File "D:/Programs Files/PyCharm Community Edition 2023.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec     pydev_imports.execfile(file, globals, locals)  # execute the script   File "D:\Programs Files\PyCharm Community Edition 2023.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile     exec(compile(contents+"\n", file, 'exec'), glob, loc)   File "E:\Python_project\nd-Mamba2-torch-main\iqa_train.py", line 152, in <module&gt;     pred = model(img)   File "D:\Programs Files\Anaconda\envs\PL-IQA\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "E:\Python_project\nd-Mamba2-torch-main\torchnssd\ex_bi_mamba2_ac.py", line 218, in forward     y_h2 = self.bi_mamba_w1(x_h2).transpose(1, 2).reshape(b, w, h, -1).transpose(1, 3)   File "D:\Programs Files\Anaconda\envs\PL-IQA\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "E:\Python_project\nd-Mamba2-torch-main\torchnssd\ex_bi_mamba2_ac.py", line 184, in forward     x1 = self.mamba2_for(x)   File "D:\Programs Files\Anaconda\envs\PL-IQA\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl     return forward_call(*input, **kwargs)   File "E:\Python_project\nd-Mamba2-torch-main\torchnssd\ex_bi_mamba2_ac.py", line 85, in forward     C.unsqueeze(2), )   File "E:\Python_project\nd-Mamba2-torch-main\torchnssd\ex_bi_mamba2_ac.py", line 126, in ssd     states = torch.einsum("bclhn, bhcl, bclhp -&gt; bchpn", B, decay_states, x)   File "D:\Programs Files\Anaconda\envs\PL-IQA\lib\site-packages\torch\functional.py", line 378, in einsum     return _VF.einsum(equation, operands)  # type: ignore[attr-defined] torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB (GPU 0; 11.99 GiB total capacity; 25.08 GiB already allocated; 0 bytes free; 25.16 GiB reserved in total by PyTorch) If reserved memory is &gt;&gt; allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF python-BaseException

**Comment by liuchenxin666** [comment]
非常感谢您的建议。
另外，我想问一下，在使用ex_bi_mamba2.py中的`BiMamba2_1D`模型时，不可以使用torch的
```
torch.use_deterministic_algorithms(True)
```
设置吗？

**Comment by Human9000** [comment]
关于你提出的这个确定性设置，我并没有尝试过，我会尽快去做相关的测试。
下面这里是一个简单的调试方法：如果你发现了这个确定性设置不可用的话，可以尝试不使用bimamba ，仅采用mambablock，进行简单测试，如果这样可行，你可以自定义或者调整我编写的bimamba模块，并且希望你能通知我，我会尽快去做这个功能的适配。如果这样仍旧不行，那说明mamba本身不支持这个功能。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年1月17日(周五) 晚上7:45
收件人: ***@***.***&gt;;
抄送: "Hao ***@***.******@***.***&gt;;
主题: Re: [Human9000/nd-Mamba2-torch] 想咨询一下显存的消耗 (Issue #34)




 
非常感谢您的建议。
 另外，我想问一下，在使用ex_bi_mamba2.py中的BiMamba2_1D模型时，不可以使用torch的
 torch.use_deterministic_algorithms(True)  
设置吗？

**Comment by liuchenxin666** [comment]
具体查看了，是在Mamba2类的ssd函数中出现的问题
```
class Mamba2(nn.Module):
    def __init__(
                 ):
    def forward(self, u: Tensor):
    
    def ssd(self, x, A, B, C):
        chunk_size = self.chunk_size
        # if x.shape[1] % chunk_size == 0:
        #
        x = x.reshape(x.shape[0], x.shape[1] // chunk_size, chunk_size, x.shape[2], x.shape[3], )
        B = B.reshape(B.shape[0], B.shape[1] // chunk_size, chunk_size, B.shape[2], B.shape[3], )
        C = C.reshape(C.shape[0], C.shape[1] // chunk_size, chunk_size, C.shape[2], C.shape[3], )
        A = A.reshape(A.shape[0], A.shape[1] // chunk_size, chunk_size, A.shape[2])
        A = A.permute(0, 3, 1, 2)
        A_cumsum = torch.cumsum(A, dim=-1)
```
最后的`torch.cumsum()`

**Comment by liuchenxin666** [comment]
这样的话，运行结果无法完全复现，确实有点头疼，我昨天尝试的训练过程，似乎有一半可能出现nan，另一半是正常训练结果。

**Comment by Human9000** [comment]
这种情况确实头疼，这个cumsum是官方指定的计算方式。

**Comment by Human9000** [comment]
你可以尝试使用两种解决方案：
1、在使用这个函数的时候临时关闭可复现的设置
2、在指定可复现设置的时候添加警告参数，这样它运行到这里不会产生错误只会产生警告，你可以正常运行
